name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 25
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-provider: basic
      - name: Make Gradle wrapper executable
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: Artifacts
          path: |
            fabric/build/libs/*.jar
            neoforge/build/libs/*.jar
          if-no-files-found: error